name: CI

on:
  push:
    branches: [develop, master, main]
    paths:
      - "**.ts"
      - "**.js"
      - "**.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - "**ignore"
      - ".github/workflows/**"
  pull_request:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Find cache of node_modules
        id: node_modules_cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules_${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      # Execute only when no cache are found
      - name: Install dependencies
        run: pnpm ci

      - name: Run static check
        run: pnpm run check

      - name: Run test
        run: pnpm test:ci
